In [36]:
import numpy as np
np.__version__


'1.26.0'

In [37]:
practice = np.array([[2, 4, 5], [7, 8, 9]])
practice

array([[2, 4, 5],
       [7, 8, 9]])

In [38]:
practice.reshape(3, 2), practice

(array([[2, 4],
        [5, 7],
        [8, 9]]),
 array([[2, 4, 5],
        [7, 8, 9]]))

In [40]:
practice.shape = (3, 2)
practice

array([[2, 4],
       [5, 7],
       [8, 9]])

In [35]:
practice_view = practice[:]
practice.reshape(3, 2)
practice_view, practice

(array([[2, 4, 5],
        [7, 8, 9]]),
 array([[2, 4, 5],
        [7, 8, 9]]))

In [34]:
practice

array([[2, 4, 5],
       [7, 8, 9]])

In [29]:
practice.shape = (1, 6)
practice

array([[2, 4, 5, 7, 8, 9]])

In [30]:
practice_view.shape

(1, 6)